version: '2.2'

services:
  plugin: 
     build: ../..
     volumes: 
      - "./test:/work/bundles/org.openhab.binding.mavlinkardupilot/target"
    
  openhab:
    image: "openhab/openhab:3.1.0-snapshot-debian"
    restart: always
    network_mode: host
    volumes:
      - "./openhab_addons:/openhab/addons"
      - "./openhab_conf:/openhab/conf"
      - "./openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
    command: "./start_debug.sh server "
